# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Autonomous Empirical Research
repo_url: 'https://github.com/autoresearch/autora-theorist-template'

theme:
  name: material

watch:
  - src

markdown_extensions:
  - pymdownx.arithmatex:
      generic: false

plugins:
  - search
  - gen-files:
      scripts:
        - mkdocs/gen_ref_pages.py
  - literate-nav:
        nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://scikit-learn.org/stable/objects.inv
  - mkdocs-jupyter:
      include_source: true
      execute: false
      ignore_h1_titles: True


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6  # required for pymdownx.arithmetex
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js  # required for pymdownx.arithmetex


nav:
- 'index.md'
- 'example.ipynb'
- Code Reference: reference/src/autora/
